# Generated by Django 4.2.4 on 2023-08-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
