# Generated by Django 4.2.5 on 2023-09-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_produto_quantidade_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacesso',
            name='data_acesso',
            field=models.DateTimeField(),
        ),
    ]
